puts "The students of my cohort at Makers Academy"
puts "----------------"
puts "Kennerdeigh"
puts "Anath"
puts "Jean-Baptiste"
puts "Erica"
puts "Georgi"
puts "Nicki"
puts "Chris"
puts "Kumy"
puts "Lara"
puts "James"
puts "Asta"
puts "Hannah"
puts "Simon"
puts "Gianni"
puts "Tom Groombridge"
puts "Tom Shacham "
puts "Jeremy"
puts "Michael"
puts "Bruce"
puts "James"
puts "Giacomo"
puts "Nisar"
puts "Peter"